---
name: "mos2_grad"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/Downloads/mos2/1/mos2/mos2_0.00_dstep1.0.json"

post_load:
 - type: poisson
   scale: 6.09e+6  # 1e+6

# for each reconstruction engine
engines:
   # how to transition from previous state to current reconstruction state
   # how to reconstruct
   # how to output/save
 - type: 'gradient'
   sim_shape: [256, 256]

   probe_modes: 4
   niter: 100
   grouping: 128

   noise_model:
     type: 'poisson'
     eps: 1.0e-3

   solvers:
     object:
       type: 'sgd'
       learning_rate: 1.0e+0
       momentum: 0.99
     probe:
       type: 'sgd'
       learning_rate: 1.0e-3
       momentum: 0.99

   regularizers:
     - type: obj_phase_l1
       cost: 5.0e+1
     #- type: obj_tikh
     #  cost: 1.0e+1

   iter_constraints: []
   group_constraints: []

   update_probe: {after: 2}
   #update_positions: {after: 30}

   save: {every: 10}
   save_images: {every: 10}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum'
     ]