---
name: "si_grad"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/Downloads/si-final4/Si_110_Sn_300kV_conv25_defocus10_tds/Si_110_Sn_300kV_conv25_defocus10_tds_199.70_dstep0.8_x80_y80_4DSTEM.raw"
  diff_step: 0.8  # mrad/px
  kv: 300.        # keV

post_load:
 - type: poisson
   scale: 14.46e+6

# initialization

init_probe:
  type: 'focused'
  conv_angle: 25  # mrad
  defocus: 100   # angstrom

init_object: 'random'

init_scan:
  type: 'raster'
  shape: [80, 80] # ny, nx
  step_size: 0.3  # angstrom

slices:
  n: 15
  total_thickness: 200

# for each reconstruction engine
engines:
   # how to transition from previous state to current reconstruction state
   # how to reconstruct
   # how to output/save
 - type: 'gradient'
   probe_modes: 4

   niter: 500
   grouping: 128

   noise_model:
     type: poisson
     eps: 1.0e-3

   solvers:
     object:
       type: 'sgd'
       learning_rate: 1.0
       momentum: 0.99
     probe:
       type: 'sgd'
       learning_rate: 1.0e-3
       momentum: 0.9
     positions:
       type: 'sgd'
       learning_rate: 3.0e-1
       momentum: 0.99

   regularizers:
     #- type: obj_recip_l1
     #  cost: 1.0e+2
     - type: obj_phase_l1
       cost: 50.0
     - type: obj_tikh
       cost: 5.0e+3

   group_constraints: []
   iter_constraints:
     - type: clamp_object_amplitude
       amplitude: 1.2
     - type: layers
       sigma: 50.0
       weight: 0.9

   update_probe: {after: 5}
   update_positions: {after: 10}

   save: {every: 10}
   save_images: {every: 2}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]
