---
name: "srtio3_exp"
backend: jax

# raw data source
raw_data:
  type: empad
  path: "~/Downloads/20241123/20241123-sto-bicrystal/acq3-pristine/scan_x128_y128.raw"
  diff_step: 0.55  # mrad/px
  kv: 300.        # keV

post_load:
  - type: scale
    scale: 0.0011534

# initialization

init_probe:
  type: 'focused'
  conv_angle: 25  # mrad
  defocus: 150   # angstrom

init_object: 'random'

init_scan:
  type: 'raster'
  shape: [128, 128] # ny, nx
  step_size: 0.52955  # angstrom
  affine: [[1.00187444, -0.03341090329], [0.0, 1.06022897]]

post_init:
 - drop_nans
 - diffraction_align

slices:
  n: 10
  total_thickness: 200

engines:
 - type: 'gradient'
   sim_shape: [192, 192]
   probe_modes: 4
   niter: 200
   grouping: 100

   noise_model:
     type: 'poisson'
     eps: 1.0e-2

   solvers:
     object:
       type: 'sgd'
       learning_rate: 1.0
       momentum: 0.99
     probe:
       type: 'sgd'
       learning_rate: 4.0e-4
       momentum: 0.9
     positions:
       type: 'sgd'
       learning_rate: 1.0e-1
       momentum: 0.99

   regularizers:
     #- type: obj_recip_l1
     #  cost: 1.0e+2
     - type: obj_phase_l1
       cost: 50.0
     - type: obj_tikh
       cost: 5.0e+3

   group_constraints: []
   iter_constraints:
     - type: clamp_object_amplitude
       amplitude: 1.5
     - type: layers
       sigma: 100.0
       weight: 0.6

   update_probe: {after: 5}
   update_positions: {after: 10}

   save: {every: 10}
   save_images: {every: 5}
   save_options:
     images: [
      'probe', 'probe_recip', 'object_phase_sum', 'object_mag_sum',
      'object_phase_stack', 'object_mag_stack'
     ]
